# Generated by Django 4.2.6 on 2023-10-21 01:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('kind', models.CharField(choices=[('стандартная', 'стандартная'), ('лаборатория', 'лаборатория')], default='стандартная', max_length=20, verbose_name='kind')),
            ],
            options={
                'verbose_name': 'audience',
                'verbose_name_plural': 'audiences',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='created')),
                ('modified', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='modified')),
                ('title', models.CharField(max_length=40, verbose_name='title')),
                ('kind', models.CharField(choices=[('лекция', 'лекция'), ('лабораторная', 'лабораторная')], max_length=40, verbose_name='title')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='created')),
                ('modified', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='modified')),
                ('role', models.CharField(choices=[('лекция', 'учитель'), ('студент', 'студент')], max_length=40, verbose_name='role')),
                ('user_name', models.CharField(max_length=40, verbose_name='user name')),
                ('user_surname', models.CharField(max_length=40, verbose_name='user surname')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_back_app.group')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_back_app.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb', models.CharField(max_length=20, verbose_name='numb')),
                ('day', models.DateTimeField(verbose_name='day')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_back_app.audience')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_back_app.group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_back_app.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_back_app.user')),
            ],
            options={
                'verbose_name': 'timetable',
                'verbose_name_plural': 'timetable',
            },
        ),
        migrations.CreateModel(
            name='GroupToStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='created')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_back_app.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_back_app.user')),
            ],
            options={
                'db_table': 'group_to_student',
                'unique_together': {('group', 'student')},
            },
        ),
    ]
